change test n

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -31,8 +31,44 @@ jobs:
       - name: Install dependencies
         run: npm install
 
-      - name: Create storageState.json from secret
-        run: echo "$STORAGE_STATE" | base64 -d > storageState.json
+      - name: name: Playwright Tests on LambdaTest
+
+on:
+  workflow_dispatch:
+  schedule:
+    - cron: '0 10 * * *'
+
+permissions:
+  contents: write
+
+jobs:
+  chrome:
+    name: Chrome Tests on LambdaTest
+    runs-on: ubuntu-latest
+
+    env:
+      STORAGE_STATE: ${{ secrets.STORAGE_STATE }}
+      LT_GRID_URL: mobile-hub.lambdatest.com
+      LT_USERNAME: ${{ secrets.USERNAME_LT }}
+      LT_ACCESS_KEY: ${{ secrets.ACCESS_KEY_LT }}
+
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v3
+
+      - name: Setup Node.js
+        uses: actions/setup-node@v4
+        with:
+          node-version: '18'
+
+      - name: Install dependencies
+        run: npm install
+
+      - name: Decode storageState.json from GitHub Secret
+        run: |
+          echo "$STORAGE_STATE" | base64 -d > storageState.json
+          echo "storageState.json content:"
+          cat storageState.json || echo "Failed to read file"
         shell: bash
           
       - name: Run Chrome tests remotely
